version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua-senha
      POSTGRES_DB: Seu-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    environment:
      DATABASE_URL: "postgresql://postgres:sua-senha@postgres:5432/Seu-db"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3081:3081"
      - "5555:5555"
      
    command: "npm start"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:


